version: '3.8'
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: flask_container
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_DB: mydb
    ports:
      - "5000:5000"
    depends_on:
      - db
